/* Course content lives here so lessons can be edited without changing the app. */
(() => {
  const sections = [
    { name: 'GDScript Fundamentals', icon: '✦', lessons: [
      ['Variables','data','A variable is a named place to keep a value so your script can use it later.','var dog_speed = 12','The dog’s speed, health and stroke count are all useful variables.','Create a variable called dog_speed with the value 20.','var dog_speed = 12',['dog_speed','20'],'var dog_speed = 20','What does the = symbol do when you write a variable?',['store','assign','put','set'],'A single = assigns a value to a name.'],
      ['Data Types','data','A data type tells Godot what kind of value it is working with: a number, text, true/false, or something else.','var dog_name: String = "Biscuit"','Names are text (String); strokes are whole numbers (int); a win flag is a bool.','Create an integer variable named strokes with the value 3.','var strokes = 0',['strokes','3'],'var strokes: int = 3','Which type is best for a whole number of strokes?',['int','integer','whole number'],'An int stores whole numbers, which makes it a good fit for a stroke count.'],
      ['Operators','data','Operators do work with values. You can add, compare, or combine them.','var total = strokes + bonus_strokes','Use arithmetic to add a stroke, and comparisons to check whether the ball is close enough.','Increase strokes by 1 using an assignment operator.','var strokes = 3\n# add one stroke',['strokes += 1'],'strokes += 1','Which operator adds one to a number?',['+=','plus equals','add'],'+= adds the right-hand value to the variable on the left.'],
      ['if Statements','logic','An if statement runs its indented block only when its condition is true.','if strokes == 1:\n    print("Hole in one!")','Ask whether the dog has reached the hole before celebrating.','Print HOLE! when ball_in_hole is true.','var ball_in_hole = true\n',['if','ball_in_hole','print'],'if ball_in_hole:\n    print("HOLE!")','When does the indented code inside an if run?',['true','condition','when the condition is true'],'The condition decides whether the indented block runs.'],
      ['else','logic','else handles the other path when an if condition is false.','if ball_moving:\n    print("Wait!")\nelse:\n    print("Your turn!")','The game can wait while the ball rolls, then let the player aim.','Add an else branch that prints READY when the ball is stopped.','if ball_moving:\n    print("Wait")\n',['else:','READY'],'else:\n    print("READY")','When does an else block run?',['false','otherwise','if the if condition is false'],'else is the fallback path for a false if condition.'],
      ['elif','logic','elif means “else if.” It checks another condition when earlier conditions were false.','if strokes == 1:\n    print("Ace!")\nelif strokes < 4:\n    print("Nice!")','Give the dog different reactions for a hole-in-one, a good round, or a rough one.','Add an elif branch that checks whether strokes is greater than 4.','if strokes == 1:\n    print("Ace!")\n',['elif','strokes > 4'],'elif strokes > 4:\n    print("Keep going!")','What does elif let you do?',['another condition','check another condition','extra condition'],'elif checks another condition in the same decision chain.'],
      ['Boolean Logic: and, or, not','logic','Boolean logic combines true/false checks. and needs both checks true; or needs either; not flips a check.','if ball_stopped and dog_ready:\n    take_shot()','A shot might be allowed only when the ball is stopped and the dog is ready.','Require both ball_stopped and dog_ready before printing AIM.','var ball_stopped = true\nvar dog_ready = true\n',['and','ball_stopped','dog_ready'],'if ball_stopped and dog_ready:\n    print("AIM")','What must be true for A and B to be true?',['both','both checks','each condition'],'and is true only when both conditions are true.'],
      ['Functions','function','A function is a named set of instructions you can run when needed. It saves you from repeating the same code.','func bark():\n    print("Woof!")','Put the dog’s bark in one function and call it whenever the ball reaches the hole.','Define a function named celebrate that prints GOOD DOG!','',['func celebrate','print','GOOD DOG'],'func celebrate():\n    print("GOOD DOG!")','Why put repeated instructions in a function?',['reuse','repeat','organize'],'A function gives instructions a name so you can reuse them.'],
      ['Function Parameters','function','Parameters are named inputs a function receives when it is called.','func cheer(message):\n    print(message)','Pass a different reaction into the dog’s cheer function for each level.','Make greet accept a parameter named player_name.','',['func greet','player_name'],'func greet(player_name):\n    print("Hello, ", player_name)','What does a parameter provide to a function?',['input','information','value'],'A parameter is an input the caller can provide.'],
      ['Return Values','function','A return value is the result a function sends back to the code that called it.','func shots_left(limit, strokes):\n    return limit - strokes','Calculate and return the remaining strokes instead of only printing them.','Return strokes + 1 from a function named next_stroke.','',['func next_stroke','return','strokes + 1'],'func next_stroke(strokes):\n    return strokes + 1','What does return do?',['sends back','gives back','result'],'return sends a result back to the caller.']
    ]},
    { name: 'Repetition & Data', icon: '⌘', lessons: [
      ['for Loops','repeat','A for loop repeats its indented block for each item in a sequence.','for hole in holes:\n    print(hole)','Visit every hole in the course to place a flag or reset a level object.','Loop through holes and print each hole.','var holes = [1, 2, 3]\n',['for','in holes','print'],'for hole in holes:\n    print(hole)','What does a for loop do?',['repeat','each item','go through each item'],'A for loop repeats once for each item in its sequence.'],
      ['while Loops','repeat','A while loop repeats as long as its condition remains true. Make sure something eventually changes that condition.','while ball_moving:\n    update_ball()','Keep checking the ball until it stops rolling.','Write a while loop that repeats while strokes is less than 3.','var strokes = 0\n',['while','strokes < 3'],'while strokes < 3:\n    strokes += 1','When does a while loop stop?',['false','condition becomes false','no longer true'],'A while loop ends when its condition becomes false.'],
      ['Arrays','collection','An array stores an ordered list of values. Items have positions, starting at index 0.','var holes = ["Pond", "Hill", "Bridge"]','Keep the course’s hole names in one array and visit them by index or item.','Create an array named hazards with two hazard names.','',['hazards','[',']',','],'var hazards = ["pond", "sand"]','What is the first index in a GDScript array?',['0','zero'],'Array positions start at index 0.'],
      ['Dictionaries','collection','A dictionary stores key-and-value pairs. Each key labels the value you want to look up.','var level = {"par": 3, "wind": 2}','Store a level’s par, wind strength and theme under readable keys.','Create a dictionary named stats with a strokes key set to 0.','',['stats','{','strokes','0','}'],'var stats = {"strokes": 0}','How do you look up a value in a dictionary?',['key','by its key','key name'],'A key is the label used to look up a dictionary value.'],
      ['Working With Collections','collection','Collections let you add, remove, inspect and loop through groups of data.','holes.append("Cloud Green")\nprint(holes.size())','Add a bonus hole to the course, then use the list’s size to show how many remain.','Add "Dog Park" to an array named holes.','var holes = ["Pond"]\n',['holes.append','Dog Park'],'holes.append("Dog Park")','What does append do to an array?',['add','adds','at the end'],'append adds a new item to the end of an array.'],
      ['Scope','structure','Scope is where a name can be used. A variable inside a function is local to that function.','var level_name = "Puddle Cup"\nfunc start_round():\n    var strokes = 0','Keep temporary shot calculations inside the function that needs them.','Create a local variable named shot_power inside shoot_ball.','func shoot_ball():\n    pass\n',['var shot_power'],'func shoot_ball():\n    var shot_power = 10','Where can a local variable usually be used?',['inside','function','scope'],'A local variable belongs to its function’s scope.'],
      ['Constants','structure','A constant is a named value that should not change while the game runs.','const MAX_STROKES = 12','Keep fixed rules like the maximum number of strokes in a constant.','Create a constant named MAX_STROKES with value 12.','',['const MAX_STROKES','12'],'const MAX_STROKES = 12','When should you use a constant?',['does not change','fixed','unchanging'],'Constants make fixed values clear and prevent accidental changes.'],
      ['Comments and Code Readability','structure','Comments are notes for people reading the script. Clear names and tidy spacing make code easier to change.','# Reset the round before the next hole\nfunc reset_round():','Leave a note explaining why a tricky dog-golf rule exists.','Add a comment that says Count the new stroke.','',['#','Count the new stroke'],'# Count the new stroke','What character begins a single-line GDScript comment?',['#','hash'],'A # starts a single-line comment in GDScript.']
    ]},
    { name: 'GDScript + Godot', icon: '◈', lessons: [
      ['What Is a Node?','godot','A node is a basic building block in a Godot game. Nodes handle jobs like drawing, physics, sound or text.','extends Node2D\nvar strokes = 0','The dog, ball, camera and score label can each be nodes with different jobs.','Write an extends line for a 2D game node.','',['extends Node2D'],'extends Node2D','What is a node?',['building block','game building block','a building block'],'Nodes are the building blocks that make up a Godot scene.'],
      ['Scenes','godot','A scene is a reusable bundle of nodes. A whole level, a dog or a golf ball can each be its own scene.','# Dog.tscn can contain a sprite, collision and script','Build the dog once as a scene, then use it in every level.','Write a comment naming a reusable Ball.tscn scene.','',['#','Ball.tscn'],'# Reusable Ball.tscn scene','What can a Godot scene represent?',['reusable','group of nodes','node tree'],'A scene is a reusable node tree that can represent a game object or level.'],
      ['Node References','godot','A node reference gives your script a way to reach another node in the scene tree.','@onready var score_label = $HUD/ScoreLabel','The ball script can find a label to update the stroke count.','Create an onready reference named score_label to $HUD/ScoreLabel.','extends Node2D\n',['@onready','score_label','$HUD/ScoreLabel'],'@onready var score_label = $HUD/ScoreLabel','What does a node reference help a script do?',['access','find','use another node'],'A reference lets a script access another node.'],
      ['_ready()','godot','Godot calls _ready() once when a node and its children are ready in the scene tree.','func _ready():\n    print("Round ready")','Set up the level or connect a label after its nodes are available.','Add a _ready function that prints ROUND READY.','extends Node\n',['func _ready','ROUND READY'],'func _ready():\n    print("ROUND READY")','When does _ready() run?',['ready','enters the scene tree','once'],'Godot calls _ready after the node and its children are ready.'],
      ['_process()','godot','Godot calls _process(delta) every rendered frame. Use it for frame-based updates that do not need physics timing.','func _process(delta):\n    rotate(delta)','Animate a floating score sparkle smoothly as frames are drawn.','Define _process with a delta parameter.','extends Node\n',['func _process','delta'],'func _process(delta):\n    pass','What is delta useful for in _process?',['time','frame time','elapsed time'],'delta is the time since the previous frame, useful for frame-rate independent changes.'],
      ['_physics_process()','godot','Godot calls _physics_process(delta) on a steady physics tick. Use it for movement and physics-related updates.','func _physics_process(delta):\n    velocity.x = speed','Update the golf ball’s movement in the physics loop.','Define _physics_process with a delta parameter.','extends Node2D\n',['func _physics_process','delta'],'func _physics_process(delta):\n    pass','Which callback is suited to physics updates?',['_physics_process','physics process'],'_physics_process runs at a fixed rate suited to physics work.'],
      ['Input','godot','Input actions turn keyboard, mouse or controller events into named controls configured in Godot.','if Input.is_action_just_pressed("shoot"):\n    shoot_ball()','Let players aim and shoot with the same named action across devices.','Check whether the shoot action was just pressed.','',['Input.is_action_just_pressed','shoot'],'if Input.is_action_just_pressed("shoot"):\n    shoot_ball()','Why use a named input action?',['multiple devices','remap','same control'],'Named actions can be mapped to different keys or devices in project settings.'],
      ['Signals','godot','A signal is an event a node emits when something happens. Other nodes can react without being tightly connected.','signal hole_completed\n# Emit when the ball reaches the cup','Let the ball announce that the hole is complete; the level can then update the score.','Declare a signal named ball_stopped.','',['signal ball_stopped'],'signal ball_stopped','What is a signal for?',['event','notify','tell other nodes'],'Signals communicate that an event happened.'],
      ['Instancing Scenes','godot','Instancing creates a copy of a saved scene while the game is running.','var ball = ball_scene.instantiate()\nadd_child(ball)','Spawn a fresh ball scene when the player starts a new hole.','Call instantiate on ball_scene and store it in new_ball.','',['instantiate()','new_ball'],'var new_ball = ball_scene.instantiate()','What does instantiate do?',['creates','copy','scene instance'],'instantiate creates a runtime copy of a PackedScene.'],
      ['Script Organization','godot','Organized scripts keep each node focused on a clear job and use descriptive names.','func reset_hole():\n    strokes = 0\n    update_score()','Keep ball movement in the ball script and scoring in a score manager.','Create a function named reset_hole.','extends Node\n',['func reset_hole'],'func reset_hole():\n    pass','Why split a game into focused scripts?',['responsibility','easier','organized'],'Focused scripts are easier to read, reuse and debug.']
    ]},
    { name: 'Game Programming', icon: '⚡', lessons: [
      ['Vectors','physics','A Vector2 stores two numbers, usually an x and y coordinate or direction.','var aim = Vector2(1, 0)','Aim the ball with a direction and strength instead of separate unrelated numbers.','Create a Vector2 named aim pointing right.','',['Vector2','aim','1','0'],'var aim = Vector2(1, 0)','What does Vector2 store?',['x and y','two numbers','position'],'Vector2 stores two components, commonly x and y.'],
      ['Movement','physics','Movement changes an object’s position over time, often using its velocity and elapsed time.','position += direction * speed * delta','Move the dog smoothly regardless of how fast the screen refreshes.','Update position using velocity multiplied by delta.','var velocity = Vector2(10, 0)\n',['position','velocity','delta'],'position += velocity * delta','Why multiply movement by delta?',['frame rate','time','consistent'],'Using elapsed time keeps movement consistent across frame rates.'],
      ['Velocity','physics','Velocity describes how fast an object moves and in which direction. In Godot 2D, it is usually a Vector2.','velocity = aim * shot_power','A golf shot gives the ball velocity in the direction the player aimed.','Set velocity to aim multiplied by shot_power.','var velocity = Vector2.ZERO\nvar aim = Vector2.RIGHT\nvar shot_power = 300\n',['velocity =','aim','shot_power'],'velocity = aim * shot_power','What two things does velocity describe?',['speed','direction','how fast and direction'],'Velocity includes both speed and direction.'],
      ['Collisions','physics','A collision happens when physics shapes touch. Godot can report the contact so your game can react.','if move_and_collide(velocity * delta):\n    print("Bonk!")','Bounce the ball off a log or stop it at the edge of the course.','Check whether move_and_collide returns a collision.','var collision = move_and_collide(velocity)\n',['if','collision'],'if collision:\n    print("Bonk!")','What does a collision shape help Godot detect?',['touch','overlap','contact'],'Collision shapes let Godot detect when physics objects touch or overlap.'],
      ['Physics Bodies','physics','Physics body nodes define how objects participate in the physics simulation. Choose a body based on how it should move.','extends RigidBody2D','A rolling golf ball can use a rigid body so Godot’s physics moves it.','Write the class line for a CharacterBody2D script.','',['extends CharacterBody2D'],'extends CharacterBody2D','Which body is commonly used for a physics-simulated ball?',['RigidBody2D','rigidbody2d'],'RigidBody2D is designed for objects moved by the physics simulation.'],
      ['Timers','physics','A Timer emits a timeout signal after a chosen delay, so you can schedule something without blocking the game.','await get_tree().create_timer(1.0).timeout\nprint("Ready!")','Wait a moment before the dog celebrates a perfect shot.','Create a one-second scene timer and await its timeout.','',['create_timer','timeout','await'],'await get_tree().create_timer(1.0).timeout','Why use a Timer instead of pausing the game?',['without blocking','other things','keeps running'],'A timer lets the rest of the game continue while time passes.'],
      ['State Machines','physics','A state machine tracks which mode an object is in and defines what it can do in each mode.','enum BallState { AIMING, ROLLING, HOLED }','The ball can switch from aiming to rolling, then to holed when it reaches the cup.','Declare an enum with AIMING and ROLLING states.','',['enum','AIMING','ROLLING'],'enum BallState { AIMING, ROLLING }','What does a state machine help organize?',['modes','states','behavior'],'States make an object’s modes and allowed behavior explicit.'],
      ['Spawning','physics','Spawning means creating game objects during play, often by instancing a scene and adding it to the tree.','var hazard = hazard_scene.instantiate()\nadd_child(hazard)','Place a new silly obstacle when the player starts a bonus course.','Instance hazard_scene and add the result as a child.','',['hazard_scene.instantiate()','add_child'],'var hazard = hazard_scene.instantiate()\nadd_child(hazard)','What is spawning?',['creating','objects during play','instantiate'],'Spawning creates objects while the game is running.'],
      ['Cameras','physics','A camera controls which part of the world the player sees. It can follow the ball during a dramatic shot.','$Camera2D.position = ball.position','Keep the action in view as the ball rolls toward a faraway hole.','Make a Camera2D current.','',['Camera2D','make_current'],'$Camera2D.make_current()','What does a game camera control?',['view','what player sees','visible area'],'A camera controls the view of the game world.'],
      ['UI','physics','User interface elements show information and controls, like score labels, buttons and a win panel.','$HUD/Score.text = "Strokes: %d" % strokes','Show the stroke count so players know how their round is going.','Set score_label.text to "Strokes: 3".','var score_label = Label.new()\n',['score_label.text','Strokes: 3'],'score_label.text = "Strokes: 3"','What should a score label help the player understand?',['game information','score','status'],'UI communicates game information and gives players controls.']
    ]},
    { name: 'Building Real Systems', icon: '✹', lessons: [
      ['Saving and Loading','systems','Saving writes useful game data to storage; loading reads it back in a later session.','var save_file = FileAccess.open("user://save.json", FileAccess.WRITE)','Remember the player’s best score or unlocked levels between runs.','Open a file at user://save.json in write mode.','',['FileAccess.open','user://save.json','WRITE'],'var file = FileAccess.open("user://save.json", FileAccess.WRITE)','Why save game data?',['later','between sessions','keep progress'],'Saving lets progress persist after the game closes.'],
      ['Reusable Systems','systems','A reusable system solves a job in a way that works in multiple levels or scenes.','func award_stroke():\n    strokes += 1\n    score_changed.emit(strokes)','Use one scoring function for every hole instead of copying scoring logic.','Create a function named award_stroke.','',['func award_stroke'],'func award_stroke():\n    pass','What makes a system reusable?',['multiple','more than one','different places'],'Reusable systems work in multiple places without duplicating logic.'],
      ['Debugging','systems','Debugging is the process of finding and fixing why code behaves differently from what you expect.','print("ball velocity: ", velocity)','Check a value at the moment a shot goes wonky, then narrow down the cause.','Print the value of strokes to the output.','var strokes = 2\n',['print','strokes'],'print(strokes)','What is a useful first debugging move?',['inspect','check values','reproduce'],'Inspect values and reproduce the problem to narrow down its cause.'],
      ['Game Architecture','systems','Architecture is how the parts of a game are divided and communicate. Clear responsibilities help a project grow.','signal score_changed(new_score)','Let the ball report events and let the level decide how to react.','Declare a score_changed signal that carries new_score.','',['signal score_changed','new_score'],'signal score_changed(new_score)','Why separate game responsibilities?',['change','maintain','easier'],'Clear responsibilities make systems easier to maintain and change.'],
      ['Optimization','systems','Optimization makes a game use fewer resources or run more smoothly. Measure first so you work on a real bottleneck.','if not visible: return','Avoid doing unnecessary work for an off-screen decoration.','Add an early return when is_visible is false.','func update_sparkle():\n',['if','return','is_visible'],'func update_sparkle():\n    if not is_visible:\n        return','What should you do before optimizing?',['measure','profile','find bottleneck'],'Measure performance first so you optimize the real bottleneck.'],
      ['Game Feel','systems','Game feel comes from the small responses that make actions satisfying: timing, animation, sound and feedback.','# Add a tiny squash when the ball lands','Make each satisfying bonk readable with a short visual reaction and clear sound.','Add a comment describing a squash effect on ball impact.','',['#','squash','impact'],'# Add squash feedback on ball impact','What contributes to game feel?',['feedback','timing','sound'],'Responsive feedback, timing, animation and sound make actions feel satisfying.'],
      ['Finishing a Game','systems','Finishing means making the game understandable and complete: clear goals, useful menus, tested levels and a proper ending.','func show_results():\n    results_panel.visible = true','Give players a clear result screen and a way to try again.','Create a function named restart_level.','',['func restart_level'],'func restart_level():\n    pass','What helps a player know a game is finished?',['ending','clear goal','results'],'A clear ending or result tells players they completed the goal.'],
      ['Exporting a Godot Game','systems','Exporting packages your project for a platform so other people can run it. Test the exported build, not only the editor.','## Export the project for your target platform','Share the dog golf game with a friend and check that the build starts correctly.','Add a comment reminding yourself to test the exported build.','',['#','exported build'],'# Test the exported build on the target platform','What is an export preset for?',['platform','target platform','package'],'An export preset packages the project for a chosen platform.']
    ]}
  ];

  const quizPresets = {
    1: { type: 'prediction', question: 'Biscuit gets one extra stroke. What number is printed?', code: 'var strokes = 2\nstrokes += 1\nprint(strokes)', choices: ['2', '3', '21'], correct: 1, explanation: 'The assignment adds one to 2, so the new value is 3.' },
    2: { type: 'type-answer', question: 'Fill in the type for a whole-number stroke count.', code: 'var strokes: ___ = 3', accepted: ['int', 'integer'], explanation: 'int is the GDScript type for whole numbers.' },
    3: { type: 'prediction', question: 'The dog gets a snack bonus. What does this print?', code: 'print(2 + 3 * 4)', choices: ['20', '14', '24'], correct: 1, explanation: 'Multiplication happens before addition, so 2 + 12 is 14.' },
    4: { type: 'bug-hunt', question: 'The dog is always celebrating. What is wrong with this check?', code: 'if health = 0:\n    print("GAME OVER")', choices: ['A single = assigns; compare with ==.', 'The message needs to be uppercase.', 'if cannot check numbers.'], correct: 0, explanation: 'An if condition checks a comparison. A single = changes a value.' },
    5: { type: 'true-false', question: 'An else block runs when the if condition is true.', code: 'if ball_moving:\n    print("Wait")\nelse:\n    print("Aim")', choices: ['True', 'False'], correct: 1, explanation: 'False. else is the fallback when the if condition is false.' },
    6: { type: 'type-answer', question: 'Which word means both conditions must be true?', code: 'if ball_stopped ___ dog_ready:', accepted: ['and'], explanation: 'and requires both checks to be true.' },
    8: { type: 'rearrange', question: 'Put the celebration function together. Move its header above the dog’s lines.', code: '', lines: ['    print("FETCH!")', 'func celebrate():', '    print("Biscuit approves!")'], correctOrder: [1, 2, 0], explanation: 'A function header comes first. Its indented instructions follow.' },
    10: { type: 'prediction', question: 'What does the function send back?', code: 'func next_stroke(strokes):\n    return strokes + 1\n\nprint(next_stroke(2))', choices: ['2', '3', '1'], correct: 1, explanation: 'next_stroke adds one, then returns 3 to the caller.' },
    11: { type: 'type-answer', question: 'One word is missing from this loop. Type it in.', code: 'for hole ___ holes:', accepted: ['in'], explanation: 'A for loop uses in between the item and collection.' },
    12: { type: 'bug-hunt', question: 'This while loop never gets to start. Spot the syntax bug.', code: 'while strokes < 3\n    strokes += 1', choices: ['The condition line needs a colon.', 'while loops cannot change variables.', 'The number must be in quotes.'], correct: 0, explanation: 'A while header ends with a colon before its indented block.' },
    13: { type: 'true-false', question: 'The first position in a GDScript array is index 1.', code: 'var holes = ["Pond", "Hill"]', choices: ['True', 'False'], correct: 1, explanation: 'False. The first item is at index 0.' },
    14: { type: 'type-answer', question: 'A dictionary uses a ___ to find the value you want.', code: 'level["___"]', accepted: ['key', 'key name'], explanation: 'The key is the label you look up in a dictionary.' },
    16: { type: 'rearrange', question: 'Put the local power calculation inside the function that uses it.', code: '', lines: ['    var shot_power = 10', 'func shoot_ball():', '    print(shot_power)'], correctOrder: [1, 0, 2], explanation: 'The function header starts the block; its local variable and use are indented inside.' },
    17: { type: 'type-answer', question: 'Which keyword declares a value that should not change?', code: '___ MAX_STROKES = 12', accepted: ['const', 'constant'], explanation: 'const marks a value as fixed.' },
    21: { type: 'bug-hunt', question: 'Why can’t this script find the score label?', code: '@onready var score_label = HUD/ScoreLabel', choices: ['A node path needs a $ before HUD.', 'Node paths must use backslashes.', 'The variable name has to be uppercase.'], correct: 0, explanation: 'The $ shorthand asks Godot for a node at that scene-tree path.' },
    22: { type: 'true-false', question: 'Godot calls _ready() after a node and its children are ready.', code: 'func _ready():\n    print("Round ready")', choices: ['True', 'False'], correct: 0, explanation: 'True. _ready() runs once after the node and its children enter the scene tree.' },
    23: { type: 'prediction', question: 'Suppose one frame has delta = 0.5. What value gets printed?', code: 'func _process(delta):\n    var sparkle_spin = delta * 2.0\n    print(sparkle_spin)', choices: ['0.5', '1.0', '2.5'], correct: 1, explanation: '0.5 multiplied by 2.0 is 1.0 for this frame.' },
    25: { type: 'bug-hunt', question: 'The shoot action is detected, but the dog never shoots. What is missing?', code: 'if Input.is_action_just_pressed("shoot"):\n    shoot_ball', choices: ['Call the function with parentheses: shoot_ball().', 'Add a second Input before shoot.', 'Change the action name to a number.'], correct: 0, explanation: 'A function name alone does not call it; add parentheses.' },
    26: { type: 'type-answer', question: 'What method sends a signal to listeners?', code: 'ball_stopped.___()', accepted: ['emit'], explanation: 'Calling emit() broadcasts the signal to connected listeners.' },
    27: { type: 'rearrange', question: 'Create the ball, place it at the tee, then add it to the scene.', code: '', lines: ['add_child(ball)', 'var ball = ball_scene.instantiate()', 'ball.position = tee_position'], correctOrder: [1, 2, 0], explanation: 'Instantiate the scene first, set it up, then add it as a child.' },
    29: { type: 'prediction', question: 'Which x value does aim.x print?', code: 'var aim = Vector2(4, -2)\nprint(aim.x)', choices: ['-2', '4', '2'], correct: 1, explanation: 'The first Vector2 number is its x component: 4.' },
    31: { type: 'true-false', question: 'Velocity describes both speed and direction.', code: 'velocity = aim * shot_power', choices: ['True', 'False'], correct: 0, explanation: 'True. Velocity combines how fast something moves and which way.' },
    32: { type: 'bug-hunt', question: 'The ball bonks the log, but this line will not parse. Spot the bug.', code: 'if move_and_collide(velocity * delta)\n    print("Bonk!")', choices: ['The if line needs a colon.', 'delta must be an integer.', 'print cannot go inside an if.'], correct: 0, explanation: 'GDScript uses a colon at the end of a control-flow header.' },
    33: { type: 'type-answer', question: 'Which body node lets physics simulate a rolling golf ball?', code: 'extends ___', accepted: ['RigidBody2D', 'rigid body 2d'], explanation: 'RigidBody2D is moved by Godot’s physics simulation.' },
    36: { type: 'rearrange', question: 'Spawn a hazard: make it, place it, then add it to the level.', code: '', lines: ['add_child(hazard)', 'var hazard = hazard_scene.instantiate()', 'hazard.position = spawn_point'], correctOrder: [1, 2, 0], explanation: 'Create the instance first, set its position, then add it to the scene tree.' },
    38: { type: 'prediction', question: 'What message appears on the scoreboard?', code: 'var strokes = 3\nprint("Strokes: %d" % strokes)', choices: ['Strokes: 3', '3 Strokes', 'Strokes: %d'], correct: 0, explanation: '%d is replaced by the stroke count, so the label reads “Strokes: 3”.' },
    39: { type: 'true-false', question: 'Saving data only changes memory; it never writes anything for a later session.', code: 'FileAccess.open("user://save.json", FileAccess.WRITE)', choices: ['True', 'False'], correct: 1, explanation: 'False. Saving writes data so it can be loaded in a later session.' },
    40: { type: 'rearrange', question: 'Put the reusable stroke helper in order.', code: '', lines: ['    score_changed.emit(strokes)', 'func award_stroke():', '    strokes += 1'], correctOrder: [1, 2, 0], explanation: 'The helper starts with a function header, then changes strokes and emits the update.' },
    41: { type: 'bug-hunt', question: 'The debug print has a tiny punctuation problem. Find it.', code: 'print("ball velocity: ", velocity', choices: ['It is missing a closing parenthesis.', 'velocity must be printed first.', 'Debug messages need a semicolon.'], correct: 0, explanation: 'The print call needs its closing parenthesis.' },
    42: { type: 'type-answer', question: 'Which keyword declares an event other nodes can listen for?', code: '___ score_changed(new_score)', accepted: ['signal'], explanation: 'The signal keyword declares an event other nodes can connect to.' },
    43: { type: 'rearrange', question: 'Skip hidden sparkle work, then update it when visible.', code: '', lines: ['    update_sparkle()', 'if not is_visible:', '    return'], correctOrder: [1, 2, 0], explanation: 'An early return skips the update when the sparkle is not visible.' },
    44: { type: 'prediction', question: 'The ball has landed. What does this print?', code: 'var landed = true\nif landed:\n    print("PLOP!")', choices: ['Nothing', 'PLOP!', 'true'], correct: 1, explanation: 'The condition is true, so the indented print runs.' },
    45: { type: 'true-false', question: 'A clear ending helps players know when the game is complete.', code: 'func show_results():\n    results_panel.visible = true', choices: ['True', 'False'], correct: 0, explanation: 'True. A result screen can make the goal and ending clear.' },
    46: { type: 'type-answer', question: 'An export preset packages your project for a target ___.', code: 'Export preset → target ___', accepted: ['platform', 'device', 'system'], explanation: 'An export preset prepares a game for a target platform.' }
  };

  const distractors = {
    data: ['It runs once every frame without being called.', 'It makes a new scene in the scene tree.'],
    logic: ['It stores a value under a name.', 'It repeats a block once for every item in a list.'],
    function: ['It stores a value that cannot change.', 'It runs automatically every physics tick.'],
    repeat: ['It sends an event to another node.', 'It creates a copy of a saved scene.'],
    collection: ['It runs every frame while the game is open.', 'It compares two values and chooses a branch.'],
    structure: ['It creates a physics collision shape.', 'It sends an event to other nodes.'],
    godot: ['It stores an ordered list of values.', 'It describes an object’s speed and direction.'],
    physics: ['It labels a value in a dictionary.', 'It runs once when a node becomes ready.'],
    systems: ['It stores a value that cannot change.', 'It repeats code once per frame.']
  };
  const normalizeChoices = (quiz, seed) => {
    if (!quiz.choices || quiz.type === 'true-false') return quiz;
    const shift = seed % quiz.choices.length;
    return {
      ...quiz,
      choices: [...quiz.choices.slice(shift), ...quiz.choices.slice(0, shift)],
      correct: (quiz.correct - shift + quiz.choices.length) % quiz.choices.length
    };
  };
  const challengeStories = [
    'A very polite goose has stolen the flag.', 'The snack cart is rolling downhill again.',
    'Biscuit’s tail just bonked the scoreboard.', 'A tiny tornado swapped all the hole signs.',
    'The golf ball has parked itself in a dog bed.', 'The crowd is cheering for the wrong ball.',
    'A suspiciously large mushroom is blocking the green.', 'The hole has wandered off to get snacks.'
  ];
  const bossNames = { 10: 'The Return of the Bounce', 18: 'The Colon Goblin', 28: 'The Scene-Stealing Slime', 38: 'Scoreboard Showdown', 46: 'The Export Yeti' };

  let id = 0;
  const lessons = sections.flatMap((section, sectionIndex) => section.lessons.map((row) => {
    id += 1;
    const [title, category, concept, example, game, task, starter, needs, solution, question, keywords, why] = row;
    const fallback = {
      type: 'multiple-choice', question: `Caddie check: ${question}`, code: example,
      choices: [why, ...distractors[category]], correct: 0, explanation: why
    };
    const quiz = normalizeChoices(quizPresets[id] || fallback, id);
    const fillBlank = id % 6 === 0;
    const broken = category === 'logic'
      ? 'if health = 0:\n    print("GAME OVER")'
      : category === 'godot'
        ? 'func _ready\n    print("Round ready")'
        : category === 'repeat'
          ? 'for hole holes:\n    print(hole)'
          : category === 'collection'
            ? 'var holes = ["Pond"\n'
            : category === 'function'
              ? 'func bark(:\n    print("Woof!")'
              : 'var dog_speed 20';
    const fixNeeds = category === 'logic' ? ['if','=='] : category === 'godot' ? ['func _ready()'] : category === 'repeat' ? ['for','in'] : category === 'collection' ? [']'] : category === 'function' ? ['func',')'] : ['='];
    const titleSlug = title.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
    const challengeType = bossNames[id] ? 'boss-challenge' : 'bonus';
    const story = challengeStories[(id - 1) % challengeStories.length];
    return {
      id, section: section.name, sectionIndex, sectionIcon: section.icon, title, category,
      difficulty: id < 11 ? 'Beginner' : id < 29 ? 'Growing' : 'Game maker',
      minutes: id < 11 ? 7 : 9, xp: 50,
      skills: [category === 'godot' ? 'Godot editor' : category === 'physics' ? 'Game systems' : 'GDScript', title],
      concept, example, game, quiz,
      fix: { type: 'bug-hunt', prompt: 'Repair this deliberately broken GDScript. Keep the idea, fix the syntax or logic.', starter: broken, required: fixNeeds, hints: ['Read the error out loud and point to the part that is not valid GDScript.','Check the punctuation and operator around the condition or declaration.','Compare your repaired line with the small example in the lesson.'], solution: category === 'logic' ? 'if health == 0:\n    print("GAME OVER")' : category === 'godot' ? 'func _ready():\n    print("Round ready")' : category === 'repeat' ? 'for hole in holes:\n    print(hole)' : category === 'collection' ? 'var holes = ["Pond"]' : category === 'function' ? 'func bark():\n    print("Woof!")' : 'var dog_speed = 20' },
      build: { type: fillBlank ? 'fill-blank' : 'write-code', prompt: fillBlank ? `Fill in the missing code: ${task}` : task, starter: `${starter || ''}${fillBlank ? `${starter ? '\n' : ''}# Fill in the missing line here\n` : ''}`, required: needs, hints: ['Start with the name or keyword the task asks you to use.','Use the tiny example above as a pattern, then change it to fit this task.','Check capitalization, punctuation and indentation in GDScript.'], solution },
      explain: { question: `In your own words: ${question}`, keywords },
      challenge: { type: challengeType, title: bossNames[id] || ['Goose on the Green', 'Snack Cart Panic', 'Tail vs. Scoreboard', 'The Great Sign Swap', 'Dog-bed Hazard', 'Crowd Control', 'Mushroom Mayhem', 'Runaway Hole'][ (id - 1) % challengeStories.length ], story, prompt: `${story} Remix your ${title.toLowerCase()} skill: ${task} Add a goofy twist of your own if you want.`, starter: '# Bonus idea: write your own twist\n', required: needs.slice(0, Math.min(2, needs.length)), solution },
      completionBadge: id === 1 ? 'First Variable' : id === 4 ? 'If Master' : id === 11 ? 'Looping' : id === 13 || id === 14 ? 'Data Hoarder' : id === 19 ? 'Godot Initiate' : id === 26 ? 'Signal Boost' : id === 29 ? 'Vector Vibes' : id === 46 ? 'Code Wizard' : null,
      slug: titleSlug
    };
  }));

  window.QuestCourse = { sections, lessons, projectPhases: [
    { name: 'PHASE 1 — THE COURSE', tasks: ['Create the main scene','Create the dog','Create the golf ball','Create a golf hole','Create terrain','Create collision'] },
    { name: 'PHASE 2 — THE SHOT', tasks: ['Implement aiming','Implement shooting','Implement ball physics','Detect when the ball stops','Detect when the ball reaches the hole','Track strokes','Calculate score'] },
    { name: 'PHASE 3 — THE GAME', tasks: ['Create level transitions','Add UI','Add restart','Add sound','Add camera movement','Add multiple levels','Add hazards'] },
    { name: 'PHASE 4 — MAKE IT DELIGHTFUL', tasks: ['Polish the game','Add animations','Add camera effects','Add funny dog reactions','Test everything','Fix bugs','Optimize','Export','PLAY THE GAME'] }
  ] };
})();
